apiVersion: v1
kind: Secret
metadata:
  name: homepage-secrets
  namespace: homepage
type: Opaque
stringData:
  HOMEPAGE_ALLOWED_HOSTS: "homepage.k3s.dawo9889-homelab.ovh,homepage.k3s.dawo9889-homelab.ovh:443"