apiVersion: v1
kind: Secret
metadata:
  name: homepage-secrets
  namespace: homepage
type: Opaque
stringData:
  # Example secrets available as HOMEPAGE_VAR_* env vars inside the container
  HOMEPAGE_VAR_EXAMPLE_TOKEN: "replace-me"